# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wq.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='wq.proto',
  package='wq',
  syntax='proto3',
  serialized_pb=_b('\n\x08wq.proto\x12\x02wq\"\xa4\x01\n\x03Msg\x12\x1a\n\x05login\x18\x01 \x01(\x0b\x32\t.wq.LoginH\x00\x12*\n\rloginReturnOk\x18\x02 \x01(\x0b\x32\x11.wq.LoginReturnOkH\x00\x12.\n\x0floginReturnFail\x18\x03 \x01(\x0b\x32\x13.wq.LoginReturnFailH\x00\x12\x1c\n\x06logout\x18\x04 \x01(\x0b\x32\n.wq.LogoutH\x00\x42\x07\n\x05union\"$\n\x06Player\x12\x0b\n\x03pid\x18\x01 \x01(\t\x12\r\n\x05level\x18\x03 \x01(\t\"$\n\x05Login\x12\x0b\n\x03pid\x18\x01 \x01(\t\x12\x0e\n\x06passwd\x18\x02 \x01(\t\"+\n\rLoginReturnOk\x12\x1a\n\x06player\x18\x01 \x01(\x0b\x32\n.wq.Player\"!\n\x0fLoginReturnFail\x12\x0e\n\x06reason\x18\x01 \x01(\t\"\x15\n\x06Logout\x12\x0b\n\x03pid\x18\x01 \x01(\tb\x06proto3')
)




_MSG = _descriptor.Descriptor(
  name='Msg',
  full_name='wq.Msg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='login', full_name='wq.Msg.login', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='loginReturnOk', full_name='wq.Msg.loginReturnOk', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='loginReturnFail', full_name='wq.Msg.loginReturnFail', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='logout', full_name='wq.Msg.logout', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='union', full_name='wq.Msg.union',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=17,
  serialized_end=181,
)


_PLAYER = _descriptor.Descriptor(
  name='Player',
  full_name='wq.Player',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pid', full_name='wq.Player.pid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='level', full_name='wq.Player.level', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=219,
)


_LOGIN = _descriptor.Descriptor(
  name='Login',
  full_name='wq.Login',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pid', full_name='wq.Login.pid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='passwd', full_name='wq.Login.passwd', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=221,
  serialized_end=257,
)


_LOGINRETURNOK = _descriptor.Descriptor(
  name='LoginReturnOk',
  full_name='wq.LoginReturnOk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='player', full_name='wq.LoginReturnOk.player', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=259,
  serialized_end=302,
)


_LOGINRETURNFAIL = _descriptor.Descriptor(
  name='LoginReturnFail',
  full_name='wq.LoginReturnFail',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reason', full_name='wq.LoginReturnFail.reason', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=304,
  serialized_end=337,
)


_LOGOUT = _descriptor.Descriptor(
  name='Logout',
  full_name='wq.Logout',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pid', full_name='wq.Logout.pid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=339,
  serialized_end=360,
)

_MSG.fields_by_name['login'].message_type = _LOGIN
_MSG.fields_by_name['loginReturnOk'].message_type = _LOGINRETURNOK
_MSG.fields_by_name['loginReturnFail'].message_type = _LOGINRETURNFAIL
_MSG.fields_by_name['logout'].message_type = _LOGOUT
_MSG.oneofs_by_name['union'].fields.append(
  _MSG.fields_by_name['login'])
_MSG.fields_by_name['login'].containing_oneof = _MSG.oneofs_by_name['union']
_MSG.oneofs_by_name['union'].fields.append(
  _MSG.fields_by_name['loginReturnOk'])
_MSG.fields_by_name['loginReturnOk'].containing_oneof = _MSG.oneofs_by_name['union']
_MSG.oneofs_by_name['union'].fields.append(
  _MSG.fields_by_name['loginReturnFail'])
_MSG.fields_by_name['loginReturnFail'].containing_oneof = _MSG.oneofs_by_name['union']
_MSG.oneofs_by_name['union'].fields.append(
  _MSG.fields_by_name['logout'])
_MSG.fields_by_name['logout'].containing_oneof = _MSG.oneofs_by_name['union']
_LOGINRETURNOK.fields_by_name['player'].message_type = _PLAYER
DESCRIPTOR.message_types_by_name['Msg'] = _MSG
DESCRIPTOR.message_types_by_name['Player'] = _PLAYER
DESCRIPTOR.message_types_by_name['Login'] = _LOGIN
DESCRIPTOR.message_types_by_name['LoginReturnOk'] = _LOGINRETURNOK
DESCRIPTOR.message_types_by_name['LoginReturnFail'] = _LOGINRETURNFAIL
DESCRIPTOR.message_types_by_name['Logout'] = _LOGOUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Msg = _reflection.GeneratedProtocolMessageType('Msg', (_message.Message,), dict(
  DESCRIPTOR = _MSG,
  __module__ = 'wq_pb2'
  # @@protoc_insertion_point(class_scope:wq.Msg)
  ))
_sym_db.RegisterMessage(Msg)

Player = _reflection.GeneratedProtocolMessageType('Player', (_message.Message,), dict(
  DESCRIPTOR = _PLAYER,
  __module__ = 'wq_pb2'
  # @@protoc_insertion_point(class_scope:wq.Player)
  ))
_sym_db.RegisterMessage(Player)

Login = _reflection.GeneratedProtocolMessageType('Login', (_message.Message,), dict(
  DESCRIPTOR = _LOGIN,
  __module__ = 'wq_pb2'
  # @@protoc_insertion_point(class_scope:wq.Login)
  ))
_sym_db.RegisterMessage(Login)

LoginReturnOk = _reflection.GeneratedProtocolMessageType('LoginReturnOk', (_message.Message,), dict(
  DESCRIPTOR = _LOGINRETURNOK,
  __module__ = 'wq_pb2'
  # @@protoc_insertion_point(class_scope:wq.LoginReturnOk)
  ))
_sym_db.RegisterMessage(LoginReturnOk)

LoginReturnFail = _reflection.GeneratedProtocolMessageType('LoginReturnFail', (_message.Message,), dict(
  DESCRIPTOR = _LOGINRETURNFAIL,
  __module__ = 'wq_pb2'
  # @@protoc_insertion_point(class_scope:wq.LoginReturnFail)
  ))
_sym_db.RegisterMessage(LoginReturnFail)

Logout = _reflection.GeneratedProtocolMessageType('Logout', (_message.Message,), dict(
  DESCRIPTOR = _LOGOUT,
  __module__ = 'wq_pb2'
  # @@protoc_insertion_point(class_scope:wq.Logout)
  ))
_sym_db.RegisterMessage(Logout)


# @@protoc_insertion_point(module_scope)
