// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wq.proto

/*
Package wq is a generated protocol buffer package.

It is generated from these files:
	wq.proto

It has these top-level messages:
	Msg
	Player
	Login
	LoginReturnOk
	LoginReturnFail
	Logout
*/
package wq

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Msg struct {
	// Types that are valid to be assigned to Union:
	//	*Msg_Login
	//	*Msg_LoginReturnOk
	//	*Msg_LoginReturnFail
	//	*Msg_Logout
	Union isMsg_Union `protobuf_oneof:"union"`
}

func (m *Msg) Reset()                    { *m = Msg{} }
func (m *Msg) String() string            { return proto.CompactTextString(m) }
func (*Msg) ProtoMessage()               {}
func (*Msg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type isMsg_Union interface {
	isMsg_Union()
}

type Msg_Login struct {
	Login *Login `protobuf:"bytes,1,opt,name=login,oneof"`
}
type Msg_LoginReturnOk struct {
	LoginReturnOk *LoginReturnOk `protobuf:"bytes,2,opt,name=loginReturnOk,oneof"`
}
type Msg_LoginReturnFail struct {
	LoginReturnFail *LoginReturnFail `protobuf:"bytes,3,opt,name=loginReturnFail,oneof"`
}
type Msg_Logout struct {
	Logout *Logout `protobuf:"bytes,4,opt,name=logout,oneof"`
}

func (*Msg_Login) isMsg_Union()           {}
func (*Msg_LoginReturnOk) isMsg_Union()   {}
func (*Msg_LoginReturnFail) isMsg_Union() {}
func (*Msg_Logout) isMsg_Union()          {}

func (m *Msg) GetUnion() isMsg_Union {
	if m != nil {
		return m.Union
	}
	return nil
}

func (m *Msg) GetLogin() *Login {
	if x, ok := m.GetUnion().(*Msg_Login); ok {
		return x.Login
	}
	return nil
}

func (m *Msg) GetLoginReturnOk() *LoginReturnOk {
	if x, ok := m.GetUnion().(*Msg_LoginReturnOk); ok {
		return x.LoginReturnOk
	}
	return nil
}

func (m *Msg) GetLoginReturnFail() *LoginReturnFail {
	if x, ok := m.GetUnion().(*Msg_LoginReturnFail); ok {
		return x.LoginReturnFail
	}
	return nil
}

func (m *Msg) GetLogout() *Logout {
	if x, ok := m.GetUnion().(*Msg_Logout); ok {
		return x.Logout
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Msg) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Msg_OneofMarshaler, _Msg_OneofUnmarshaler, _Msg_OneofSizer, []interface{}{
		(*Msg_Login)(nil),
		(*Msg_LoginReturnOk)(nil),
		(*Msg_LoginReturnFail)(nil),
		(*Msg_Logout)(nil),
	}
}

func _Msg_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Msg)
	// union
	switch x := m.Union.(type) {
	case *Msg_Login:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Login); err != nil {
			return err
		}
	case *Msg_LoginReturnOk:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.LoginReturnOk); err != nil {
			return err
		}
	case *Msg_LoginReturnFail:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.LoginReturnFail); err != nil {
			return err
		}
	case *Msg_Logout:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Logout); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Msg.Union has unexpected type %T", x)
	}
	return nil
}

func _Msg_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Msg)
	switch tag {
	case 1: // union.login
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Login)
		err := b.DecodeMessage(msg)
		m.Union = &Msg_Login{msg}
		return true, err
	case 2: // union.loginReturnOk
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(LoginReturnOk)
		err := b.DecodeMessage(msg)
		m.Union = &Msg_LoginReturnOk{msg}
		return true, err
	case 3: // union.loginReturnFail
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(LoginReturnFail)
		err := b.DecodeMessage(msg)
		m.Union = &Msg_LoginReturnFail{msg}
		return true, err
	case 4: // union.logout
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Logout)
		err := b.DecodeMessage(msg)
		m.Union = &Msg_Logout{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Msg_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Msg)
	// union
	switch x := m.Union.(type) {
	case *Msg_Login:
		s := proto.Size(x.Login)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Msg_LoginReturnOk:
		s := proto.Size(x.LoginReturnOk)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Msg_LoginReturnFail:
		s := proto.Size(x.LoginReturnFail)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Msg_Logout:
		s := proto.Size(x.Logout)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Player struct {
	Pid   string `protobuf:"bytes,1,opt,name=pid" json:"pid,omitempty"`
	Level string `protobuf:"bytes,3,opt,name=level" json:"level,omitempty"`
}

func (m *Player) Reset()                    { *m = Player{} }
func (m *Player) String() string            { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()               {}
func (*Player) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Player) GetPid() string {
	if m != nil {
		return m.Pid
	}
	return ""
}

func (m *Player) GetLevel() string {
	if m != nil {
		return m.Level
	}
	return ""
}

type Login struct {
	Pid    string `protobuf:"bytes,1,opt,name=pid" json:"pid,omitempty"`
	Passwd string `protobuf:"bytes,2,opt,name=passwd" json:"passwd,omitempty"`
}

func (m *Login) Reset()                    { *m = Login{} }
func (m *Login) String() string            { return proto.CompactTextString(m) }
func (*Login) ProtoMessage()               {}
func (*Login) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Login) GetPid() string {
	if m != nil {
		return m.Pid
	}
	return ""
}

func (m *Login) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

type LoginReturnOk struct {
	Player *Player `protobuf:"bytes,1,opt,name=player" json:"player,omitempty"`
}

func (m *LoginReturnOk) Reset()                    { *m = LoginReturnOk{} }
func (m *LoginReturnOk) String() string            { return proto.CompactTextString(m) }
func (*LoginReturnOk) ProtoMessage()               {}
func (*LoginReturnOk) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *LoginReturnOk) GetPlayer() *Player {
	if m != nil {
		return m.Player
	}
	return nil
}

type LoginReturnFail struct {
	Reason string `protobuf:"bytes,1,opt,name=reason" json:"reason,omitempty"`
}

func (m *LoginReturnFail) Reset()                    { *m = LoginReturnFail{} }
func (m *LoginReturnFail) String() string            { return proto.CompactTextString(m) }
func (*LoginReturnFail) ProtoMessage()               {}
func (*LoginReturnFail) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *LoginReturnFail) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type Logout struct {
	Pid string `protobuf:"bytes,1,opt,name=pid" json:"pid,omitempty"`
}

func (m *Logout) Reset()                    { *m = Logout{} }
func (m *Logout) String() string            { return proto.CompactTextString(m) }
func (*Logout) ProtoMessage()               {}
func (*Logout) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Logout) GetPid() string {
	if m != nil {
		return m.Pid
	}
	return ""
}

func init() {
	proto.RegisterType((*Msg)(nil), "wq.Msg")
	proto.RegisterType((*Player)(nil), "wq.Player")
	proto.RegisterType((*Login)(nil), "wq.Login")
	proto.RegisterType((*LoginReturnOk)(nil), "wq.LoginReturnOk")
	proto.RegisterType((*LoginReturnFail)(nil), "wq.LoginReturnFail")
	proto.RegisterType((*Logout)(nil), "wq.Logout")
}

func init() { proto.RegisterFile("wq.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 268 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x51, 0x4d, 0x4b, 0xc4, 0x30,
	0x10, 0x6d, 0xb7, 0x36, 0xda, 0x91, 0x65, 0x35, 0x8a, 0x14, 0x4f, 0x1a, 0x3c, 0xe8, 0xa5, 0xa8,
	0x7b, 0xf2, 0x24, 0x78, 0x90, 0x1e, 0x14, 0x65, 0xfe, 0x41, 0x65, 0x43, 0x29, 0x86, 0xa4, 0x9f,
	0x16, 0x7f, 0xa7, 0x7f, 0x48, 0x32, 0x89, 0x62, 0xeb, 0xde, 0xe6, 0xcd, 0x7b, 0xaf, 0xf3, 0x5e,
	0x03, 0x7b, 0x63, 0x93, 0xd5, 0xad, 0xe9, 0x0d, 0x5f, 0x8c, 0x8d, 0xf8, 0x0a, 0x21, 0x7a, 0xee,
	0x4a, 0x7e, 0x0e, 0xb1, 0x32, 0x65, 0xa5, 0xd3, 0xf0, 0x2c, 0xbc, 0xdc, 0xbf, 0x4d, 0xb2, 0xb1,
	0xc9, 0x9e, 0xec, 0x22, 0x0f, 0xd0, 0x31, 0xfc, 0x0e, 0x96, 0x34, 0xa0, 0xec, 0x87, 0x56, 0xbf,
	0xbc, 0xa7, 0x0b, 0x92, 0x1e, 0xfe, 0x4a, 0x7f, 0x88, 0x3c, 0xc0, 0xa9, 0x92, 0xdf, 0xc3, 0xea,
	0xcf, 0xe2, 0xb1, 0xa8, 0x54, 0x1a, 0x91, 0xf9, 0x68, 0x66, 0xb6, 0x54, 0x1e, 0xe0, 0x5c, 0xcd,
	0x2f, 0x80, 0x29, 0x53, 0x9a, 0xa1, 0x4f, 0x77, 0xc8, 0x07, 0xde, 0x67, 0x86, 0x3e, 0x0f, 0xd0,
	0x73, 0x0f, 0xbb, 0x10, 0x0f, 0xba, 0x32, 0x5a, 0x5c, 0x03, 0x7b, 0x55, 0xc5, 0xa7, 0x6c, 0xf9,
	0x01, 0x44, 0x75, 0xb5, 0xa1, 0x56, 0x09, 0xda, 0x91, 0x1f, 0x43, 0xac, 0xe4, 0x87, 0x74, 0x09,
	0x12, 0x74, 0x40, 0xdc, 0x40, 0x4c, 0x31, 0xb6, 0x18, 0x4e, 0x80, 0xd5, 0x45, 0xd7, 0x8d, 0x1b,
	0x2a, 0x9c, 0xa0, 0x47, 0x62, 0x0d, 0xcb, 0x49, 0x6d, 0x2e, 0x80, 0xd5, 0x74, 0xd5, 0xff, 0x44,
	0x0a, 0xe9, 0x72, 0xa0, 0x67, 0xc4, 0x15, 0xac, 0x66, 0x75, 0xed, 0xf7, 0x5b, 0x59, 0x74, 0x46,
	0xfb, 0xa3, 0x1e, 0x89, 0x53, 0x60, 0xae, 0xe1, 0xff, 0x4c, 0x6f, 0x8c, 0x5e, 0x70, 0xfd, 0x1d,
	0x00, 0x00, 0xff, 0xff, 0xdd, 0xcf, 0xee, 0x39, 0xcd, 0x01, 0x00, 0x00,
}
